platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target '--Project Name--' do
  pod 'SnapKit', '~> 4.0.0'
  target '--Project Name--Tests' do
    inherit! :search_paths
  end
  target '--Project Name--UITests' do
    inherit! :search_paths
  end
end
