platform :ios, "12.0"
inhibit_all_warnings!

target "--Project Name--" do
  target "--Project Name--Tests" do
    inherit! :search_paths
  end
  target "--Project Name--UITests" do
    inherit! :search_paths
  end
end
