load(
    "//Configurations:project_configuration.bzl",
    "project_configuration",
)
load(
    "//Configurations:xcode_build_settings.bzl",
    "xcode_build_settings",
)
load(
    "//Configurations:code_sign.bzl",
    "CODE_SIGN_IDENTITY_DEBUG",
    "CODE_SIGN_IDENTITY_RELEASE",
    "DEVELOPMENT_TEAM_DEBUG",
    "DEVELOPMENT_TEAM_RELEASE",
    "PROVISIONING_PROFILE_SPECIFIER_DEBUG",
    "PROVISIONING_PROFILE_SPECIFIER_RELEASE",
)

BUNDLE_IDENTIFIER_DEBUG = "__BUNDLE_ID__-Debug"
BUNDLE_IDENTIFIER_ADHOC = "__BUNDLE_ID__-AdHoc"
BUNDLE_IDENTIFIER_RELEASE = "__BUNDLE_ID__"

configuration = project_configuration()

if configuration == "debug":
    BUNDLE_IDENTIFIER = BUNDLE_IDENTIFIER_DEBUG
elif configuration == "adhoc":
    BUNDLE_IDENTIFIER = BUNDLE_IDENTIFIER_ADHOC
elif configuration == "release":
    BUNDLE_IDENTIFIER = BUNDLE_IDENTIFIER_RELEASE
else:
    fail("Unsupported configuration: {}".format(configuration))

apple_bundle(
    name = "__PROJECT_NAME__",
    extension = "app",
    binary = ":__PROJECT_NAME__Binary",
    info_plist = "InfoPlists/__PROJECT_NAME__-Info.plist",
    info_plist_substitutions = {
        "PRODUCT_BUNDLE_IDENTIFIER": BUNDLE_IDENTIFIER,
    },
)

apple_binary(
    name = "__PROJECT_NAME__Binary",
    srcs = [
        "Sources/__PROJECT_NAME__/AppDelegate/AppDelegateMain.swift",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    configs = xcode_build_settings(
        bundle_identifier_debug = BUNDLE_IDENTIFIER_DEBUG,
        bundle_identifier_release = BUNDLE_IDENTIFIER_RELEASE,
        development_team_debug = DEVELOPMENT_TEAM_DEBUG,
        development_team_release = DEVELOPMENT_TEAM_RELEASE,
        code_sign_identity_debug = CODE_SIGN_IDENTITY_DEBUG,
        code_sign_identity_release = CODE_SIGN_IDENTITY_RELEASE,
        provisioning_profile_specifier_debug = PROVISIONING_PROFILE_SPECIFIER_DEBUG,
        provisioning_profile_specifier_release = PROVISIONING_PROFILE_SPECIFIER_RELEASE,
    ),
)

xcode_workspace_config(
    name = "workspace",
    src_target = ":__PROJECT_NAME__",
    action_config_names = {
        "profile": "Profile",
    },
)
