load(
    "//Configurations:project_configuration.bzl",
    "project_configuration",
)
load(
    "//Configurations:xcode_build_settings.bzl",
    "xcode_build_settings",
)
load(
    "//Configurations:code_sign.bzl",
    "DEVELOPMENT_TEAM",
    "CODE_SIGN_IDENTITY",
    "PROVISIONING_PROFILE_SPECIFIER",
)

BUNDLE_IDENTIFIER_DEBUG = "__BUNDLE_ID__-Debug"
BUNDLE_IDENTIFIER_ADHOC = "__BUNDLE_ID__-AdHoc"
BUNDLE_IDENTIFIER_RELEASE = "__BUNDLE_ID__"

configuration = project_configuration()

if configuration == "debug":
    BUNDLE_IDENTIFIER = BUNDLE_IDENTIFIER_DEBUG
elif configuration == "adhoc":
    BUNDLE_IDENTIFIER = BUNDLE_IDENTIFIER_ADHOC
elif configuration == "release":
    BUNDLE_IDENTIFIER = BUNDLE_IDENTIFIER_RELEASE
else:
    fail("Unsupported configuration: {}".format(configuration))

apple_bundle(
    name = "__PROJECT_NAME__Bundle",
    extension = "app",
    binary = ":__PROJECT_NAME__Binary",
    info_plist = "InfoPlists/__PROJECT_NAME__-Info.plist",
    info_plist_substitutions = {
        "PRODUCT_BUNDLE_IDENTIFIER": BUNDLE_IDENTIFIER,
    },
)

apple_binary(
    name = "__PROJECT_NAME__Binary",
    srcs = [
        "Dummy.swift",
    ],
    deps = [
        "//Sources/__PROJECT_NAME__:__PROJECT_NAME__",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    configs = xcode_build_settings(
        bundle_identifier = BUNDLE_IDENTIFIER,
        development_team = DEVELOPMENT_TEAM,
        code_sign_identity = CODE_SIGN_IDENTITY,
        provisioning_profile_specifier = PROVISIONING_PROFILE_SPECIFIER,
    ),
)

xcode_workspace_config(
    name = "workspace",
    workspace_name = "__PROJECT_NAME__",
    src_target = ":__PROJECT_NAME__Bundle",
    action_config_names = {
        "profile": "Profile",
    },
)
