lane :sign do
  match(app_identifier: ["--BundleID---Debug"], type: "development", readonly: true)
  match(app_identifier: ["--BundleID---AdHoc"], type: "adhoc", readonly: true)
  match(app_identifier: ["--BundleID--"], type: "appstore", readonly: true)
end

lane :bootstrap do
  sh "cd .. && summon/bin pod install"
  sh "cd .. && summon/bin carthage bootstrap --platform ios --cache-builds"
end
