platform :ios, "13.0"

target "--PROJECT_NAME--" do
  pod "Steroid"
  pod "Steroid/UIKit13"
  pod "AppDelegate"

  target "--PROJECT_NAME--Tests" do
    inherit! :search_paths
  end
  target "--PROJECT_NAME--UITests" do
    inherit! :search_paths
  end
end
