load(
    "//Configurations:xcode_build_settings.bzl",
    "xcode_build_settings",
)
load(
    "//Configurations:code_sign.bzl",
    "DEVELOPMENT_TEAM",
    "CODE_SIGN_IDENTITY",
    "PROVISIONING_PROFILE_SPECIFIER_UI_TESTS",
)

BUNDLE_IDENTIFIER = "__BUNDLE_ID__-Debug.UITests"

apple_test(
    name = "__PROJECT_NAME__UITests",
    is_ui_test = True,
    ui_test_target_app = "//:__PROJECT_NAME__Bundle",
    srcs = glob([
        "*.swift",
    ]),
    frameworks = [
        "$PLATFORM_DIR/Developer/Library/Frameworks/XCTest.framework",
    ],
    info_plist = "Info.plist",
    info_plist_substitutions = {
        "PRODUCT_BUNDLE_IDENTIFIER": BUNDLE_IDENTIFIER,
    },
    configs = xcode_build_settings(
        bundle_identifier = BUNDLE_IDENTIFIER,
        development_team = DEVELOPMENT_TEAM,
        code_sign_identity = CODE_SIGN_IDENTITY,
        provisioning_profile_specifier = PROVISIONING_PROFILE_SPECIFIER_UI_TESTS,
    ),
    visibility = [
        "//:",
    ],
)
