load(
    "@build_bazel_rules_swift//swift:swift.bzl",
    "swift_library",
)

swift_library(
    name = "__PROJECT_NAME__Tests",
    srcs = glob([
        "*.swift",
    ]),
    visibility = [
        "//:__PROJECT_NAME__Tests",
    ],
)
