load(
    "@bazel_tools//tools/build_defs/repo:git.bzl",
    "git_repository",
)

git_repository(
    name = "build_bazel_rules_apple",
    commit = "4715a6d6abf8a48b71ed6295ee6b370a7634461b",
    remote = "https://github.com/bazelbuild/rules_apple.git",
)

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@com_google_protobuf//:protobuf_deps.bzl",
    "protobuf_deps",
)

protobuf_deps()

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

http_archive(
    name = "AppDelegate",
    sha256 = "166d67a0d6d8c0a7c6d8ea0822cfec20809cfc191405027e0933a364f8b0f70a",
    strip_prefix = "AppDelegate-0.2.0",
    urls = [
        "https://github.com/jasonnam/AppDelegate/archive/0.2.0.zip",
    ],
)
